name: Release

on:
  push:
    tags:
      - 'v*'
      - '!v*beta*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write # 允许工作流程写入仓库内容

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: '20.13.1'
          registry-url: 'https://registry.npmjs.org'
      - run: npm install -g pnpm@9.1.0
      - run: pnpm install
      - run: pnpm run utils:build
      - run: npx changelogithub
        env:
          GITHUB_TOKEN: '${{ secrets.MY_GITHUB_TOKEN }}'
      - run: |
          cd ./packages/utils
          ls -l
          cat .npmrc
          npm publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
